# Generated by Django 4.1.3 on 2023-03-27 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code for the course, e.g. 'W7', 'W1'", max_length=30
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name for the course, without the term or teacher e.g. 'INT./ADV. Handbuilding', 'Beginner Wheel",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "db_table": "course",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        help_text="e.g. '2nd Floor Wheel', or '301'", max_length=300
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="Building address", max_length=300
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Wheel', 'Handbuilding', 'Glaze'",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "location",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the term, e.g. 'Spring 2023', or, 'Summer-8-Week 2023'",
                        max_length=200,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("current", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "term",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=200, unique=True)),
                ("dob", models.DateTimeField(blank=True, null=True)),
                ("current_student", models.BooleanField(default=False)),
                ("current_teacher", models.BooleanField(default=False)),
                ("current_staff", models.BooleanField(default=False)),
                ("current_admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="measure.user",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("last_update", models.DateTimeField()),
            ],
            options={
                "db_table": "account",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_piece_id", models.IntegerField(default=1)),
                (
                    "length",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "width",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "height",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "size",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("bisque_fired", models.BooleanField(blank=True, null=True)),
                ("glaze_fired", models.BooleanField(blank=True, null=True)),
                ("damaged", models.BooleanField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="measure.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="measure.user"
                    ),
                ),
            ],
            options={
                "db_table": "piece",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("user_transaction_number", models.IntegerField(default=1)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_type", models.CharField(blank=True, max_length=100)),
                ("note", models.CharField(blank=True, max_length=1000)),
                (
                    "piece",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="measure.piece",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="measure.user",
                    ),
                ),
            ],
            options={
                "db_table": "ledger",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CourseInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the course instance, e.g. 'W15 INT/ADV Wheel Throwing w/ Haakon', or 'ST4 Glass Casting w/ Jessi'",
                        max_length=1000,
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100)),
                ("weekday", models.CharField(blank=True, max_length=100)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="measure.course",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="measure.location",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(related_name="students", to="measure.user"),
                ),
                (
                    "teachers",
                    models.ManyToManyField(related_name="teachers", to="measure.user"),
                ),
                (
                    "term",
                    models.ForeignKey(
                        help_text="Term the course instance is in. e.g., 'Spring 2023', or, 'Summer-8-Week 2023'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="measure.term",
                    ),
                ),
            ],
            options={
                "db_table": "course_instance",
                "managed": True,
            },
        ),
    ]
