# Generated by Django 4.1.3 on 2023-04-19 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GHPUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("email", models.EmailField(blank=True, max_length=200, unique=True)),
                ("current_student", models.BooleanField(default=False)),
                ("current_staff", models.BooleanField(default=False)),
                ("current_admin", models.BooleanField(default=False)),
                ("last_measure_date", models.DateField(null=True)),
                ("consent", models.BooleanField(default=False)),
                ("consent_date", models.DateField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ghp_user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "ghp_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="measure.ghpuser",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("last_update", models.DateTimeField()),
            ],
            options={
                "db_table": "account",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ghp_user_piece_id", models.IntegerField(default=1)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "length",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "width",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "height",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "size",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("course_number", models.CharField(blank=True, max_length=4)),
                ("piece_description", models.CharField(blank=True, max_length=1000)),
                ("glaze_description", models.CharField(blank=True, max_length=1000)),
                (
                    "glaze_temp",
                    models.CharField(
                        choices=[
                            ("10", "Δ 10"),
                            ("6", "Δ 6"),
                            ("2", "Δ 2"),
                            ("014", "Δ 014"),
                            ("04", "Δ 04"),
                            ("None", "None"),
                        ],
                        default="Δ 10",
                        max_length=4,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=1000)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("bisque_fired", models.BooleanField(blank=True, null=True)),
                ("glaze_fired", models.BooleanField(blank=True, null=True)),
                (
                    "ghp_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="measure.ghpuser",
                    ),
                ),
            ],
            options={
                "db_table": "piece",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("ghp_user_transaction_number", models.IntegerField(default=1)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_type", models.CharField(blank=True, max_length=100)),
                ("note", models.CharField(blank=True, max_length=1000)),
                (
                    "ghp_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="measure.ghpuser",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="measure.piece",
                    ),
                ),
            ],
            options={
                "db_table": "ledger",
                "managed": True,
            },
        ),
        migrations.AddConstraint(
            model_name="piece",
            constraint=models.CheckConstraint(
                check=models.Q(("length__gte", 0.5)),
                name="length_gte_0.5",
                violation_error_message="Length must be at least 0.5 inches",
            ),
        ),
        migrations.AddConstraint(
            model_name="piece",
            constraint=models.CheckConstraint(
                check=models.Q(("width__gte", 0.5)),
                name="width_gte_0.5",
                violation_error_message="Width must be at least 0.5 inches",
            ),
        ),
        migrations.AddConstraint(
            model_name="piece",
            constraint=models.CheckConstraint(
                check=models.Q(("height__gte", 3.0)),
                name="height_gte_3.0",
                violation_error_message="Height must be at least 3 inches",
            ),
        ),
    ]
