# Generated by Django 4.1.13 on 2024-02-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ghp_user_name", models.CharField(blank=True, max_length=100)),
                ("piece_date", models.DateField(blank=True, null=True)),
                ("length", models.DecimalField(decimal_places=1, max_digits=5)),
                ("width", models.DecimalField(decimal_places=1, max_digits=5)),
                ("height", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "handles",
                    models.DecimalField(decimal_places=0, default=0, max_digits=2),
                ),
                (
                    "size",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("course_number", models.CharField(blank=True, max_length=4)),
                (
                    "bisque_temp",
                    models.CharField(
                        choices=[("06", "Δ 06 (Cone 06)"), ("None", "None")],
                        default="06",
                        max_length=4,
                    ),
                ),
                (
                    "glaze_temp",
                    models.CharField(
                        choices=[
                            ("10", "Δ 10 (Cone 10)"),
                            ("6", "Δ 6 (Cone 6)"),
                            ("Lust", "Luster"),
                            ("04", "Δ 04 (Cone 04)"),
                            ("None", "None"),
                        ],
                        default="10",
                        max_length=4,
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        blank=True,
                        choices=[("Bisque", "Bisque"), ("Glaze", "Glaze")],
                        max_length=6,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "piece_location",
                    models.CharField(
                        choices=[("Greenwich", "Greenwich"), ("Chelsea", "Chelsea")],
                        default="Chelsea",
                        max_length=10,
                    ),
                ),
                ("printed", models.BooleanField(default=False)),
                ("printed_date", models.DateField(blank=True, null=True)),
                ("number_printed", models.IntegerField(default=0)),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="measure.piece"
                    ),
                ),
            ],
            options={
                "db_table": "piece_receipt",
                "managed": True,
            },
        ),
    ]
