# Generated by Django 4.1.3 on 2023-04-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="glaze_description",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="piece",
            name="note",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="piece",
            name="piece_description",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
