# Generated by Django 4.1.3 on 2023-04-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piece",
            name="bisque_fired",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="piece",
            name="glaze_fired",
            field=models.BooleanField(default=False),
        ),
    ]
