# Generated by Django 4.1.3 on 2023-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="ghp_user_transaction_number",
            field=models.IntegerField(default=None),
        ),
    ]
