# Generated by Django 4.1.3 on 2023-03-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
