# Generated by Django 4.1.3 on 2023-04-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
