# Generated by Django 4.1.3 on 2024-02-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0002_piecereceipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ghpuser",
            name="current_location",
            field=models.CharField(
                choices=[
                    ("Greenwich", "Greenwich"),
                    ("Chelsea", "Chelsea"),
                    ("Both", "Both"),
                ],
                default="Chelsea",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="piece_location",
            field=models.CharField(
                choices=[("Greenwich", "Greenwich"), ("Chelsea", "Chelsea")],
                default="Chelsea",
                max_length=10,
            ),
        ),
    ]
