# Generated by Django 4.1.3 on 2023-10-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0002_alter_ledger_ghp_user_transaction_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("auto_bisque_fee", "AUTO: Bisque Firing Fee"),
                    ("auto_glaze_fee", "AUTO: Glaze Firing Fee"),
                    ("auto_refund_bisque_fee", "AUTO: Refund Bisque Firing Fee"),
                    ("auto_refund_glaze_fee", "AUTO: Refund Glaze Firing Fee"),
                    ("auto_user_add_firing_credit", "AUTO: User Add Firing Credit"),
                    ("auto_gh_add_firing_credit", "AUTO: GH Add Firing Credit"),
                    ("auto_gh_add_misc_credit", "AUTO: GH Add Misc Credit"),
                    ("auto_gh_add_misc_charge", "AUTO: GH Add Misc Charge"),
                    ("manual_gh_add_misc_credit", "MANUAL: GH Add Misc Credit"),
                    ("manual_gh_add_misc_charge", "MANUAL: GH Add Misc Charge"),
                ],
                max_length=100,
            ),
        ),
    ]
