# Generated by Django 4.1.3 on 2023-03-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0002_piece_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseinstance",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="measure.course",
            ),
        ),
        migrations.AlterField(
            model_name="courseinstance",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="measure.location",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="measure.courseinstance",
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="term",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
