# Generated by Django 4.1.3 on 2023-04-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0002_piece_glaze_description_piece_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piece",
            name="glaze_temp",
            field=models.CharField(
                choices=[
                    ("10", "Cone 10"),
                    ("06", "Cone 06"),
                    ("04", "Cone 04"),
                    ("02", "Cone 02"),
                    ("14", "Cone 14"),
                    ("None", "None"),
                ],
                default="Cone 10",
                max_length=4,
            ),
        ),
    ]
