# Generated by Django 4.1.13 on 2023-12-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measure", "0003_alter_ledger_transaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ghpuser",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="piece",
            name="bisque_fired",
        ),
        migrations.RemoveField(
            model_name="piece",
            name="glaze_description",
        ),
        migrations.RemoveField(
            model_name="piece",
            name="glaze_fired",
        ),
        migrations.RemoveField(
            model_name="piece",
            name="piece_description",
        ),
        migrations.AddField(
            model_name="ghpuser",
            name="current_location",
            field=models.CharField(
                choices=[
                    ("Greenwich", "Greenwich"),
                    ("Chelsea", "Chelsea"),
                    ("Both", "Both"),
                ],
                default="Greenwich",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="piece",
            name="piece_location",
            field=models.CharField(
                choices=[("Greenwich", "Greenwich"), ("Chelsea", "Chelsea")],
                default="Greenwich",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="bisque_temp",
            field=models.CharField(
                choices=[("06", "Δ 06 (Cone 06)"), ("None", "None")],
                default="06",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="glaze_temp",
            field=models.CharField(
                choices=[
                    ("10", "Δ 10 (Cone 10)"),
                    ("6", "Δ 6 (Cone 6)"),
                    ("014", "Δ 014 (Cone 014)"),
                    ("04", "Δ 04 (Cone 04)"),
                    ("None", "None"),
                ],
                default="10",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="height",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="piece",
            name="length",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="piece",
            name="width",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
