# Generated by Django 4.1.3 on 2024-02-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0003_alter_ghpuser_current_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="piecereceipt",
            name="piece_number",
            field=models.IntegerField(default=1),
        ),
    ]
