# Generated by Django 4.1.3 on 2024-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0004_piecereceipt_piece_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piecereceipt",
            name="piece_location",
            field=models.CharField(
                choices=[("Greenwich", "Jones St."), ("Chelsea", "Chelsea")],
                default="Chelsea",
                max_length=10,
            ),
        ),
    ]
