# Generated by Django 4.1.3 on 2023-03-28 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="piece",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="measure.piece",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="height",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="piece",
            name="length",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="piece",
            name="size",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="piece",
            name="width",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
