# Generated by Django 4.1.3 on 2024-02-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0004_remove_ghpuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
