# Generated by Django 4.1.3 on 2024-07-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0005_alter_piecereceipt_piece_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piecereceipt",
            name="piece_location",
            field=models.CharField(
                choices=[("Greenwich", "Greenwich"), ("Chelsea", "Chelsea")],
                default="Chelsea",
                max_length=10,
            ),
        ),
    ]
