# Generated by Django 4.1.3 on 2023-03-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0005_alter_ledger_piece_alter_piece_height_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="GHPUser",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="user",
            new_name="ghp_user",
        ),
        migrations.RenameField(
            model_name="ledger",
            old_name="user",
            new_name="ghp_user",
        ),
        migrations.RenameField(
            model_name="ledger",
            old_name="user_transaction_number",
            new_name="ghp_user_transaction_number",
        ),
        migrations.RenameField(
            model_name="piece",
            old_name="user",
            new_name="ghp_user",
        ),
        migrations.RenameField(
            model_name="piece",
            old_name="user_piece_id",
            new_name="ghp_user_piece_id",
        ),
        migrations.AlterModelTable(
            name="ghpuser",
            table="ghp_user",
        ),
    ]
