# Generated by Django 4.2.20 on 2025-06-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0006_alter_piecereceipt_piece_location"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="piece",
            name="length_and_width_lte_21.0",
        ),
        migrations.AlterField(
            model_name="ghpuser",
            name="last_measure_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piece",
            name="bisque_temp",
            field=models.CharField(
                choices=[("06", "Δ 06 (Cone 06)"), ("None", "None")],
                default="None",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="glaze_temp",
            field=models.CharField(
                choices=[
                    ("10", "Δ 10 (Cone 10)"),
                    ("6", "Δ 6 (Cone 6)"),
                    ("Lust", "Luster"),
                    ("04", "Δ 04 (Cone 04)"),
                    ("None", "None"),
                ],
                default="None",
                max_length=4,
            ),
        ),
        migrations.AddConstraint(
            model_name="piece",
            constraint=models.CheckConstraint(
                check=models.Q(("length__lte", 21.0), ("width__lte", 21.0)),
                name="length_and_width_lte_21.0",
                violation_error_message="Length and width must be less than or equal to 21 inches",
            ),
        ),
    ]
