# Generated by Django 4.2.22 on 2025-08-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measure", "0007_remove_piece_length_and_width_lte_21_0_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ghpuser",
            name="current_location",
            field=models.CharField(
                choices=[
                    ("Greenwich", "Greenwich"),
                    ("Chelsea", "Chelsea"),
                    ("Barrow", "Barrow"),
                    ("Both", "Both"),
                ],
                default="Chelsea",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="piece_location",
            field=models.CharField(
                choices=[
                    ("Greenwich", "Greenwich"),
                    ("Chelsea", "Chelsea"),
                    ("Barrow", "Barrow"),
                ],
                default="Chelsea",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="piecereceipt",
            name="piece_location",
            field=models.CharField(
                choices=[
                    ("Greenwich", "Greenwich"),
                    ("Chelsea", "Chelsea"),
                    ("Barrow", "Barrow"),
                ],
                default="Chelsea",
                max_length=10,
            ),
        ),
    ]
