# Generated by Django 4.2.22 on 2025-08-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measure", "0008_alter_ghpuser_current_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piece",
            name="bisque_temp",
            field=models.CharField(
                choices=[("06", "Bisque (Δ 06)"), ("None", "None")],
                default="None",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="piecereceipt",
            name="bisque_temp",
            field=models.CharField(
                choices=[("06", "Bisque (Δ 06)"), ("None", "None")],
                default="06",
                max_length=4,
            ),
        ),
    ]
